### ISSUE TITLE
Process program's response

### ISSUE THREAD

**Issue by ivankravets** [smartanthill/zepto-compiler#3]
See entrance point: 
https://github.com/smartanthill/smartanthill2_0/blob/43694cd67b5c6fe25e8cb1b0d0a4b440341ada7f/smartanthill/device/device.py#L87

**Comment by marcosbracco** [comment]
I just pushed a first version of this development.
Please see https://github.com/smartanthill/smartanthill-zepto-compiler/blob/develop/tests/test_api.py#L131

Currently is returning a dictionary with field_name : value pairs
Is this ok? How is best return format ?

**Comment by ivankravets** [comment]
Thanks! It is enough for beginning :+1:
