### ISSUE TITLE
ZeptoProgram.compile: handle raw params

### ISSUE THREAD

**Issue by ivankravets** [smartanthill/zepto-compiler#4]
Currently you expect that all income params to `compile(params)` will be casted to type from `manifest.xml`:

``` python
    dynamic_data = {
        "PARAM1": 10
    }
```

As we can see, `PARAM1` is casted to `INT`. However, I don't know from User's side which is type for such param. Yes, I can add additional logic and analyse `manifest.xml` and `<request>` data, but I think that this area should be delegated to `ZeptoCompiler`. What I have from user?
- name of param
- value of param (without casting). It can be `int, str, float` or etc. 

I propose to make casting within ZC and report to upper layer with specified exception when error.

For example, both of these data are valid from user side:

```
    dynamic_data1 = {
        "PARAM1": 10
    }

    dynamic_data2 = {
        "PARAM1": "10"
    }
```

See https://github.com/smartanthill/smartanthill-zepto-compiler/blob/develop/tests/test_api.py#L37

For you it looks simple - just `int()` under `try/catch`, because currently we have only 1 type of argument (int-based).

What do you think?

**Comment by marcosbracco** [comment]
Simple solution right now, if string, compiler will try validate it for a number literal.
See
https://github.com/smartanthill/smartanthill-zepto-compiler/blob/develop/tests/test_api.py#L185
https://github.com/smartanthill/smartanthill-zepto-compiler/blob/develop/tests/test_api.py#L201
