### ISSUE TITLE
Handle raw Command&Control response

### ISSUE THREAD

**Issue by ivankravets** [smartanthill/zepto-compiler#6]
Link: https://github.com/smartanthill/smartanthill-zepto-compiler/blob/develop/tests/test_api.py#L131

Currently, ZC waits from upper layer for RESPONSE which is equal to `<response>` field. It was a temporary solution. ZC should handle full RESPONSE from Command&Control level. This RESPONSE isn't documented in our docs, but I'll explain it in a few words.
# Response Format

`RESPONSE_HEADER | PAYLOAD`

`RESPONSE_HEADER` is `encoded uint16`, where resulted `uint16` is equal to:
`0-3bits` currently is predefined to 0 (flags)
`4-15bits` is equal to size of payload data in bytes
## Response Payload

`TYPE_OF_FRAME1 | DATA1 | TYPE_OF_FRAME N | DATA N`

`TYPE_OF_FRAME` is 1byte. `0` means that ZEPTO_VM_USE_SIMPLE_FRAME. More details in code: https://github.com/smartanthill/smartanthill-simpleiot/blob/develop/src/simpleiot/siot_cc_protocol.c#L74

The response consists of frames. What does mean this frame? The frames are result for ZC.Program. For example,
Result with 1 frame:

``` js
return Temperature.Execute();
```

Result with 2 frames

``` js
return [Tem1.Execute(), Temp2.Execute()];
```

`ZC.Program.parse_reponse` should return to upper layer DATA according  "plugin's manifest <response> fields". If result consists from more then 1 frame, then results should be returned via array/list `[]` or tuple `(,)`
# Real example

Ping plugin: https://github.com/smartanthill/smartanthill2_0-embedded/blob/develop/firmware/src/plugins/ping/manifest.xml

The opcode/response for Ping plugin will be `0x20 0x00 0x01`. Where encoded-uint16 `0x20` is `0x20 >> 4` == 0x02. `0x02` - means 2bytes of payload. Then let's parse payload serially: next byte is `TYPE_OF_FRAME`, and next bytes are data according "plugin's manifest <response> fields".

P.S: @nobugs-hare @divanchykhin please correct me if something  is wrong.

**Comment by marcosbracco** [comment]
I have updated `process_response`, with the following limitations:
- If suplied data buffer is bigger than header payload size, buffer is trimmed. Extra data is lost. See https://github.com/smartanthill/smartanthill-zepto-compiler/blob/develop/tests/test_api.py#L150
- TYPE_OF_FRAME is read as an encoded-unsigned, but actually discarded. At least until I get better understanding about how to process it.
- When more than one frame in response, frames are assumed to be in the same order as they where invoked.
  i.e:

``` javascript
return [Tem1.Execute(), Temp2.Execute()];
```

response should contain first frame from `Tem1` and second from `Tem2`

See https://github.com/smartanthill/smartanthill-zepto-compiler/blob/develop/tests/test_api.py#L180

The returned result is a list `[ ]` also using the same order.

``` javascript
[{'xyz': 29.8}, {'xyz': 30.0}]
```

**Comment by ivankravets** [comment]
Thanks a lot!!! :+1: 

I've just delegated SACC response to SA Zepto Compiler https://github.com/smartanthill/smartanthill2_0/commit/5ebbac9f68b19b830de02161e060647c1d214b88
