### ISSUE TITLE
Raise CompilerError with reason (message)

### ISSUE THREAD

**Issue by ivankravets** [smartanthill/zepto-compiler#7]
See log below where we launch https://github.com/smartanthill/smartanthill2_0-embedded/blob/develop/firmware/src/plugins/pin_digital_write/manifest.xml

I inputed "-1" which is invalid value and expected `InvalidRequestParam`(or similar). However, `CompilerError` is also OK, but why it is without reason? I see that you print something to `stdout`, like " line 1:0 extraneous input '-' expecting <INVALID>...".

Question: How is difficult to raise exception with reason/value? Like, 

``` python
raise CompilerError("line 1:0 extraneous input '-' expecting <INVALID>; Stage 'parameter' giving up")
```
# Log

```
2015-08-07 21:26:02+0300 [api] Received 'EXECUTE' request with key 'device.128.DigitWrite' and data={'value': '-1'}
2015-08-07 21:26:02+0300 [-] line 1:0 extraneous input '-' expecting <INVALID>
2015-08-07 21:26:02+0300 [-] Stage 'parameter' giving up
2015-08-07 21:26:02+0300 [api.rest#error] Unhandled Error
    Traceback (most recent call last):
      File "/Volumes/SOFT/Projects/GitHub/smartanthill/smartanthill2_0/smartanthill/api/service.py", line 77, in request
        return hobj.handle(data)
      File "/Volumes/SOFT/Projects/GitHub/smartanthill/smartanthill2_0/smartanthill/device/api.py", line 39, in handle
        self._bodypart_name, data)
      File "/Volumes/SOFT/Projects/GitHub/smartanthill/smartanthill2_0/smartanthill/device/device.py", line 83, in execute_bodypart
        return self.run_program(program, request_fields)
      File "/Volumes/SOFT/Projects/GitHub/smartanthill/smartanthill2_0/.tox/develop/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
        return _inlineCallbacks(None, gen, Deferred())
    --- <exception caught here> ---
      File "/Volumes/SOFT/Projects/GitHub/smartanthill/smartanthill2_0/.tox/develop/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
        result = g.send(result)
      File "/Volumes/SOFT/Projects/GitHub/smartanthill/smartanthill2_0/smartanthill/device/device.py", line 88, in run_program
        opcode = zp.compile(parameters)
      File "/Volumes/SOFT/Projects/GitHub/smartanthill-zepto-compiler/origin/smartanthill_zc/api.py", line 165, in compile
        compiler, parameters, Ctx.PARAM)
      File "/Volumes/SOFT/Projects/GitHub/smartanthill-zepto-compiler/origin/smartanthill_zc/parse_js.py", line 111, in create_parameters
        compiler.check_stage('parameter')
      File "/Volumes/SOFT/Projects/GitHub/smartanthill-zepto-compiler/origin/smartanthill_zc/compiler.py", line 133, in check_stage
        self.raise_error()
      File "/Volumes/SOFT/Projects/GitHub/smartanthill-zepto-compiler/origin/smartanthill_zc/compiler.py", line 140, in raise_error
        raise CompilerError()
    smartanthill_zc.errors.CompilerError:
```

**Comment by marcosbracco** [comment]
I made some changes to error reporting, now `CompilerError` has a `text` attribute with an array of error messages. See
https://github.com/smartanthill/smartanthill-zepto-compiler/blob/develop/tests/test_api.py#L239

```
    except errors.CompilerError as e:
        assert e.text == [
            "line 1, Value 100000.0 outside valid range [-32768, 32767]",
            "line 1, Value -1.0 outside valid range [0, 255]"]
```

This is still sub-optimal, but at least an improvement.
Also parameters value also support constant expressions, like `2 + 3`, See
https://github.com/smartanthill/smartanthill-zepto-compiler/blob/develop/tests/test_api.py#L205

There are two thing to discuss for a really better error report.

ZeptoCompiler error reporting is thought from the usual non-interactive compiler idea. You make a program (takes some time to make it), then you give the program to the compiler (compiler takes some time to process it), and last the compiler will return some output or an error log with all the errors found. In this schema, compiler usually will try not to give up on the first problem found, but will try to continue process as much as it can and then give up with a list of all problems found so far.
This schema is very good for non-interactive long running compilations, but rather awful for interactive use like manual execution of body parts.
- So, we may need to discuss where interactive use will be the rule, so to change the way errors are handled, or figure out how to find a compromise that works for all the use cases.
- Or where the compiler should support two similar but slightly different API, one for interactive body part execution and other for non-interactive compilation. And try to make the best for each case, using the particularities of each case

What do you think?

**Comment by marcosbracco** [comment]
I have made changes to the way parameters are manipulated.
- Parameters are now only allowed as `Execute` arguments (`BodyPart.Execute(PARAM1, PARAM2)`). Use of parameters in any other place of the code will result in some type conversion error.
- Parameters value can be `int`, `float` or `str` but is always converted to float first, (as `float(params[name])` ).
- Constant expressions on parameters are no longer supported.
- Parameter values are inserted just before writing the opcodes, after all compilation. This means that second time we call `zp.compile(..)` only parameters values are replaced, resulting in much more lightweight implementation. See api.ZeptoProgram.compile 
  https://github.com/smartanthill/smartanthill-zepto-compiler/blob/develop/smartanthill_zc/api.py#L153

I think this will be better for our current needs of parameters,
Comments?

**Comment by ivankravets** [comment]
Thanks! `e.text` is good, generally in Python world it is equal to Exception.value. I mean, that your current `Exception.text is the same that generally means Exception.value`. Like, RAW data.

However, end develop doesn't use this property. You need to overload `__str__` method and return readable message. I propose you to look into this example form doc: https://docs.python.org/2/tutorial/errors.html#user-defined-exceptions

What do I mean? When I want to know raw value of exception - I'll use `e.value`, but when I need `representation` message  - I'll use `"Your exception %s" % e`.

P.S: I think that you can join all these mini-messages(logs) into one line via `;`. Or need to see in practice. 

```
```

**Comment by marcosbracco** [comment]
I did a quick overload of `__str__`, let me know what is the best format for the client to use.

**Comment by ivankravets** [comment]
Thanks! See result:
![SmartAnthill Zepto Compiler Error 1](http://i57.tinypic.com/24ngtfr.jpg)
![SmartAnthill Zepto Compiler Error 2](http://i60.tinypic.com/11j7s4w.jpg)

P.S: I propose to split these messages with `;` with space after ";", for good reading.

**Comment by ivankravets** [comment]
@marcosbracco Could I ask you to split these messages via `;` and close this issue? Thanks!
